### ISSUE TITLE
Nexus file creation crashes when encountering an empty scan in the  .spec file

### ISSUE THREAD

**Issue by AvonReppert** [dschick/pyEvalData#27]
If you have for some reaseon an empty scan in the spec file, the generation of the nexus file fails with the following error message. 

![grafik](https://user-images.githubusercontent.com/36692180/142836380-004630ab-fbf9-4dec-9fcb-750693e8753a.png)

**Comment by AvonReppert** [comment]
The current workaround is that you can search in the spec file for the line
"Scan aborted after 0 points." 
and delete these scans manually

**Comment by dschick** [comment]
could you checkout #32 and test it with your empty scans in your SPEC file?

**Comment by AvonReppert** [comment]
yes great now it works I think you can merge this branch into develop.
