### ISSUE TITLE
Handling of missing attributes of spec file

### ISSUE THREAD

**Issue by AvonReppert** [dschick/pyEvalData#28]
Using these settings for importing the spec file: 
![grafik](https://user-images.githubusercontent.com/36692180/142843807-9a05eb44-35cd-47ff-bad5-4e3ef8582e38.png)

I get these error messages:
![grafik](https://user-images.githubusercontent.com/36692180/142843858-3ab6cee3-586e-403a-9e94-bf20cd6f8395.png)

This does not prevent the execution of the code but could probably be improved. Or is the mistake on my side?

**Comment by dschick** [comment]
Thanks for spotting.

I think this is an error message specific for spyder as it does not happen for other IDEs.

However, I will try to catch it in order to avoid this disruption.

**Comment by dschick** [comment]
fixed by #31
