### ISSUE TITLE
offset subtraction in  plot_scans method missing

### ISSUE THREAD

**Issue by AvonReppert** [dschick/pyEvalData#29]
It would be nice if it were possible to subtract an offset, such as t0 for a pump-probe experiment in the  plot_scans method of the Evaluation class. 

optional handles such as xOffset and yOffset could be introduced

**Comment by dschick** [comment]
Hi @AleksUDKM ,

in general you can add any offset directly in the `clist` or `cdef` attributes of the `Evaluation` class.
So if you have a motor and a counter you want to plot, e.g.:
```
s = Evaluation(...)
s.xcol = 'delay'
s.clist = ['apd']
```
you can use the following syntax for offseting and even scaling them:
```
s.xcol = 'delay+3'
s.clist = ['10*(apd-5)']
```
Please be aware, that you always have to use the full counter name for indexing.

In the `fit_scan_sequence()` method, there is also an option to `offset_t0` of the x-axis in case your fit function contains a parameter named `t0`.

Does this solves your issue?

**Comment by AvonReppert** [comment]
Ah yes that is useful and solves my issue. 

A follow up question would then be if I can also subtract two counters when for example calculating XMCD contrast

**Comment by AvonReppert** [comment]
I quickly checked and it works nicely also when adding two counter variables. 
This minimal exam
```
spec = ped.io.Spec(file_name='2021-11-vonReppert.spec',
                   file_path='SpecFile/',
                   use_nexus=True,
                   force_overwrite=False,
                   update_before_read=False,
                   read_and_forget=True)`
s = ped.Evaluation(spec)
cdef = {     'pumped'      : 'AcqBcSP',
             'unpumped'    : 'AcqBcSU',
             'pumpedMagnet': 'AcqBcSPM',
             'XMCD'        : '(AcqBcSPM - AcqBcSP)/(AcqBcSPM + AcqBcSP)' 
            }

s.cdef              = cdef
s.propagate_errors  = propagate_errors

scan  = 543
s.xcol = 'Delay+1487.75'
s.clist = ['XMCD']
s.plot_scans([scan],False)
```
![grafik](https://user-images.githubusercontent.com/36692180/143013087-f67b2fe2-8fdc-4b1c-b81d-56d4877cc978.png)

**Comment by dschick** [comment]
sure, just give it a try :)
you also have a few mathematical functions available, see:
`s.math_keys`.
So you can do also things like:
```
clist = ['(pumped-unpumped)/mean(unpumped[delay < 0])']
```

Check also the option for `s.propagate_errors` which handles the order of the evaluation of your counter statment and possbile averaging. 
As an exmaple, if you have a relative signal `pumped/unpumped` you want to average over 5 scans: `s.propagate_errors = False` will first calculate the relative signal and then do the averaging. So the errors will result from the `std` of the relative signal.

If `s.propagate_errors = True`, first the counters `pumped` and `unpumped` are averaged and then the reative signal is calculated and the error is calculated by propper error propagation (which is done automatically for you)
