### ISSUE TITLE
ndarray from ragged nested sequences

### ISSUE THREAD

**Issue by AvonReppert** [dschick/pyEvalData#33]
The provided code example:
```
scanSequence = array([
        # scan list   ,  parameters
        [[1]        , 'no aperture 1130eV'], 
        [[2]        , 'with aperture 1130eV'],        
        [[3]        , 'with aperture 1132eV'],
    ])
```

creates the following warning that I am currently ignoring:
"Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  scanSequence = np.array( ["
  
 I do not know how to set this mixed data type in the numpy array so that it will be handled correctly in the future:

Actually I would like to plot a "Temperature series" and read the sample temperature as a data label from a counter in a .spec file. This manual workaround shown below, works for now, but also yields the aforementioned warning.

```
scanSequence = np.array( [
        # scan list   ,  parameters
        [[491]        , '50 K'], 
        [[505]        , '70 K'],        
        [[518]        , '75 K'],
        [[520]        , '80 K'],
        [[521]        , '110 K'],   
        [[522]        , '130 K'],   
    ])   
s.plot_scan_sequence(scanSequence,title_text =r"XMCD Dy40   on resonance  1295 eV $8\,\mathrm{\frac{mJ}{\,cm^2}}$",
                     sequence_type = "text", xtext = "t (ps)", ytext ="raw XMCD",                     xlims=[tMin, tMax], ylims = [0,1])
```

**Comment by dschick** [comment]
please use only `list` and NOT `np.array` for creating the `scanSequence`.
I will add some flexibility to enable also `tuple` as valid data type for a sequence enty, but `np.array` wont work.

**Comment by AvonReppert** [comment]
Thanks, yes it works like this without a warning:
```
scanSequence = [
        # scan list   ,  parameters
        [[491]        , '50 K'], 
        [[505]        , '70 K'],        
        [[518]        , '75 K'],
        [[520]        , '80 K'],
        [[521]        , '110 K'],   
        [[522]        , '130 K'],   
    ]    
plt.figure()
s.plot_scan_sequence(scanSequence,title_text =r"XMCD Dy40   on resonance  1295 eV $8\,\mathrm{\frac{mJ}{\,cm^2}}$",
                     sequence_type = "text", xtext = "t (ps)", ytext ="raw XMCD",
                     xlims=[tMin, tMax], ylims = [0,1])
````
