### ISSUE TITLE
Start and Stop scan numbers when importing spec files

### ISSUE THREAD

**Issue by EmCeBeh** [dschick/pyEvalData#5]
In the pal-fel branch, the function to load spec files of palEvalData  already accepts a `start_scan` number as input. A `stop_scan` number would be great, too.

Further one might want to include this feature in the master branch aswell?

**Comment by dschick** [comment]
I guess one shoudl also have an option to provide a list of scan numbers to read as 1st option.
if this this not given the start and stop numbers will be read.

**Comment by dschick** [comment]
we should also consider having the `file_format` for situations with split data files

**Comment by dschick** [comment]
this is now include for the `source` to handle `scan_start_number` and `scan_stop_number`
