### ISSUE TITLE
use_nexus file does not work with nexusformat==1.0.1 

### ISSUE THREAD

**Issue by AvonReppert** [dschick/pyEvalData#56]
The read-in of a *.spec  file into a NeXus does not work using a recent version of the nexusformat package

`source = Spec(name, path, use_nexus=True)`

It yields errors such as this one:
![image](https://github.com/dschick/pyEvalData/assets/36692180/a8c2f0d9-e1a5-4803-8f8c-f9d222548d0f)

falling back to `nexusformat==0.7.1` works
otherwise one can fall back to `source = Spec(name, path, use_nexus=False)`

**Comment by dschick** [comment]
hi @AvonReppert 

Thanks for spotting this error. I can confirm this behaviour.

PR #57 should fix the issue. Could you please test it?

**Comment by AvonReppert** [comment]
Yes it seems to work  now. Thanks for the immediate fix.

**Comment by dschick** [comment]
Great, so issue has been solved by PR #57 and is closed
