### ISSUE TITLE
Custom counters do not work with plotScans when binning is turned off

### ISSUE THREAD

**Issue by EmCeBeh** [dschick/pyEvalData#9]
When binning is set to `False` in `plotScans` and a custom counter `XXX` was defined in `cList`, there will be an error in line 539 that there is `no field of name XXX`.

maybe it is because...
usually `concatData[x]` is called, where `x` is one of  `baseCounters`, now it is called with one of  `cList` ?

**Comment by dschick** [comment]
#10 should fix this problem

thanks for finding this bug
